### ISSUE TITLE
Unable to call parent function from VueTables component

### ISSUE THREAD

**Issue by demetrius-edelin** [matfish2/vue-tables#100]
- Vue.js version: 1.0.26
- consumed using: Laravel 5.3 (webpack)
- FULL error message (including stack trace):

> [Vue warn]: Invalid expression. Generated function body:  scope.$parent.deleteMe({scope.id})

- relevant code: 
```

templates: {
        edit: "<a href='#!/{id}/edit'><i class='glyphicon glyphicon-edit'></i></a>",
        delete: "<a href='javascript:void(0);' @click='$parent.deleteMe({id})'>
                      <i class='glyphicon glyphicon-erase'></i></a>"
      },
```
I am not able to make a call to parent function from the component (I tried option "compileTemplates = true", still the same). Any suggestion?

Thank you,
demetrius-edelin

**Comment by matfish2** [comment]
This seems like a clear indicator that you don't have an id property on at least one of your row objects. This is causing the placeholder not to be replaced thus passing an invalid function call.
Please check your dataset.

**Comment by demetrius-edelin** [comment]
Oh, my mistake when building this example. The main point is that $parent is not visible. To show this, I modified to:
```

templates: {
        edit: "<a href='#!/{id}/edit'><i class='glyphicon glyphicon-edit'></i></a>",
        delete: "<a href='javascript:void(0);' @click='$parent.deleteMe()'>
                      <i class='glyphicon glyphicon-erase'></i></a>"
      },
```

and added this to Vue methods:

```
        var mainVue = new Vue({
            el: "#people",
              methods: {
                deleteMe: function() {
                    alert('delete');
                },
             ....

```
And after that, I am getting this error:

> TypeError: scope.$parent.deleteMe is not a function
> return scope.columns;

Btw, I really love this component! Thank you for the reply.

**Comment by matfish2** [comment]
Are you embedding the table component inside another component?

**Comment by demetrius-edelin** [comment]
I copied the example from here:

[https://jsfiddle.net/matfish2/f5h8xwgn/?utm_source=website&utm_medium=embed&utm_campaign=f5h8xwgn](https://jsfiddle.net/matfish2/f5h8xwgn/?utm_source=website&utm_medium=embed&utm_campaign=f5h8xwgn)

and added it in Laravel with 

> npm install vue-tables

I am importing the module using Elixir + Browserify with the syntax (in 'bootstrap.js' file):
```

window.Vue = require('vue');
window.VueTables = require('vue-tables');
```

and then use it in the page as instructed:

```
    Vue.use(VueTables.client, {
        compileTemplates: true,
....
}

       var mainVue = new Vue({
            el: "#people", ...
```

I am still learning Vue, but this error happened every  time I installed this component. And also $parent works fine in other components, like **vue-modal**.

Thank you for the help!

**Comment by matfish2** [comment]
I was unable to replicate this problem. Can you send me your HTML?

**Comment by demetrius-edelin** [comment]
Here is a clean Laravel install with only Vue-Tables installed, as copied from fiddle:

[https://www.dropbox.com/s/epfrs8ywi3jjsk8/app.tar.gz?dl=0](https://www.dropbox.com/s/epfrs8ywi3jjsk8/app.tar.gz?dl=0)

Try to click on Delete icon (after all npm and composer installs) and you'll get that error.

**Comment by matfish2** [comment]
On first glance I already see that you instantiate `vue` twice. Once in `welcome.blade.php` on the `body` tag, and another on app.js, on `#people`. This can easily cause conflicts.

**Comment by demetrius-edelin** [comment]
Yes, I missed it before putting the package up, but this is not the cause. Meanwhile I switched on dispatching events for edit and delete too, but this breaks the templating for them. I am very intrigued why $parent does not work, but still not able to tell (after a ton of investigation).

Thank you again.

**Comment by matfish2** [comment]
I am using this plugin on a daily basis and I never had this problem. I am pretty sure it has to do with you code. Should you discover otherwise please let me know.
