### ISSUE TITLE
Row click without jquery?

### ISSUE THREAD

**Issue by gurpal2000** [matfish2/vue-tables#101]
Hi is there an event emitted for row click so that one can use the events: attrib?

Examples i've seen seem to require jquery (this.$on('vue-tables.row-click')) ?
How does one do it without jquery?

I have tried:

```
events: {
            'vue-tables.row-click': function(row) {
                console.log('here ', row);
            }
        }
```

- Vue.js version: 1.0.26
- vue-tables: 1.4.0

**Comment by matfish2** [comment]
That's not jquery. It is a native vue event listener

**Comment by gurpal2000** [comment]
Nevermind. I realised that this is working in the master.
When is the next release coming ;-)
thx
