### ISSUE TITLE
Filtering row if contains string

### ISSUE THREAD

**Issue by KerMiiTT** [matfish2/vue-tables#102]
Hi,

How can I filter a column data who contains string like ".html" and ".txt" before display the table ?

can you give me an example plz ?

Thx.

**Comment by matfish2** [comment]
The question is somewhat vague. Assuming you are filtering by column (i.e `filterByColumn:true`) and want to set an initial query on a column, you can manipulate the query property in your `ready` method. E.g

`this.$refs.myTable.query.myColumn = '.html'`
