### ISSUE TITLE
Use HTML in heading

### ISSUE THREAD

**Issue by successamp** [matfish2/vue-tables#103]
- Vue.js version: 1.0.26
- consumed using: webpack
- FULL error message (including stack trace): N/A

First of all, thank you very much for the library.  It's been great to work with so far.  I'm running up against an issue, and I wanted to get your input on the best way to tackle it.

I have a table with a checkbox in the first column.  You can select multiple checkboxes and hit a delete button.  It will prompt and delete all selected rows.  This works just fine.  The specification for the page requires that the heading be a "select all" checkbox.  That way you can check one select box, it will select all items, and hitting the delete button will delete them all.

The problem I'm running in to is that I can't set HTML for the heading value.  All HTML is escaped leaving me unable to create a functioning header.
```
options: {
	headings: {
		checkbox: "<div class=\"checkbox\"><input type=\"checkbox\" id=\"select-all-checkbox\" name=\"select-all-checkbox\" v-model=\"selectAll\"><label for=\"select-all-checkbox\"></label></div>",
	}
}
```

Is there any way you can think of to pass HTML/template to the heading without doing a custom template for the whole table?

Thank you!

**Comment by matfish2** [comment]
Headings don't support HTML content at the moment. I am inclined not to change it unless it is proven to be a common request.
 
To get your code to work you need to fork the repo and:
A. Change the heading interpolators from double to triple curly braces to support HTML (`table-template.html:42`)
B. Manually compile the heading to account for vue specific logic (such as `v-model`), similar to what I do on `compile-templates.js`.

**Comment by Jasper9041** [comment]
I was trying this as well. Would be a great feature!

**Comment by matfish2** [comment]
Added. To avoid triggering the sort functionality inadvertently use `e.stopPropagation`

**Comment by Jasper9041** [comment]
Wonderful! Thank you very much.

**Comment by successamp** [comment]
Perfect, thank you!
