### ISSUE TITLE
Order of colums

### ISSUE THREAD

**Issue by Jasper9041** [matfish2/vue-tables#104]
Hi, I was just wondering if there is any way to change the order of columns?

To be more  specific: I would like to have a template custom column with checkboxes in it. I'm trying to get this column to display in front of everything else. Is this possible?

**Comment by matfish2** [comment]
Columns - including custom columns -are displayed in the order in which they appear in the `columns` prop. If you leave off custom columns they will be appended at the end.

**Comment by Jasper9041** [comment]
Great, did not try that. Thanks!
