### ISSUE TITLE
Uncaught TypeError: Cannot read property 'nodeType' of undefined

### ISSUE THREAD

**Issue by calvinmuller** [matfish2/vue-tables#105]
- VueTables version: 1.5.6
- Vue.js version: 1.0.26
- consumed using: webpack
- FULL error message (including stack trace):  

Uncaught TypeError: Cannot read property 'nodeType' of undefined
compileNode	@	?d41d:7097
compile	@	?d41d:6876
Vue.$compile	@	?d41d:9491
ready	@	ready.js?a6ef:3

- relevant code: ready.js mixin
- steps for reproducing the issue: just load a page with the table component on it

**Comment by matfish2** [comment]
Unable to replicate. (Also both the demo and the options are working on the latest dist version, and there is no error). Please try to delete the folder from your node_modules and reinstall.

**Comment by calvinmuller** [comment]
That's so weird, I switch to 1.5.5 and it works fine. Ill see what I can find. thanks

**Comment by calvinmuller** [comment]
<tr v-el:headings>

This was added to the new template and I used a custom one, fixed now. Thanks
