### ISSUE TITLE
Jquery dependency ?

### ISSUE THREAD

**Issue by ValentinCreative** [matfish2/vue-tables#106]
- Vue.js version: 1.0.26
- consumed using: webpack
- FULL error message (including stack trace):
```
init-date-filters.js?c237:17 Uncaught ReferenceError: $ is not defined(anonymous function) 
```

I've got this error. Does jQuery is required for this component ?

**Comment by matfish2** [comment]
No. It is only reauired if you want to use date filers which are built on top of daterangepicker
