### ISSUE TITLE
Latest vue release breaks vue-tables?

### ISSUE THREAD

**Issue by westwick** [matfish2/vue-tables#107]
It looks like something in the newest version of vue may have broke this package? When I downgrade back to 1.0.26 everything works fine, then when I upgrade to 1.0.27 it breaks, however removing the `<v-client-table>` component fixes it and allows my application to work again. Sorry I can't provide more detail, it still might be something in my own implementation of vue-tables but thought I would report it in case others have issues as well. Will update if I find any other information.

- Vue.js version: just upgraded from 1.0.26 to 1.0.27
- consumed using: webpack
- FULL error message (including stack trace): Uncaught TypeError: Cannot read property 'scope' of undefined (in vue.common.js line 4751)

**Comment by westwick** [comment]
I forked your jsfiddle client-side demo and simpy replaced the vue version (to 1.0.27) and it did cause the table to break with the same error message I posted: https://jsfiddle.net/b4jg0cse/1/

**Comment by matfish2** [comment]
As it turns out the `$refs` functionality was broken in the last update. The problem was caused by a `v-ref` on the pagination component. I've removed it and resorted to the less accurate and more prone to errors `$children[0]` instead, until the issue is fixed.

**Comment by tinchox5** [comment]
The same happened to me. I rolled back to 1.0.26
