### ISSUE TITLE
moment is not defined when using toMomentFormat option

### ISSUE THREAD

**Issue by CarlEdmondson** [matfish2/vue-tables#108]
When I set the toMomentFormat option I get the error `Uncaught ReferenceError: moment is not defined`.

Here is the app.js before it is bundled by browserify:
```
import Vue from 'vue';
import moment from 'moment';

import VueTables from 'vue-tables';

Vue.use(VueTables.client, {}, {template: require('./components/vue-tables/template.html')});

new Vue({
	el: '#app',
	data: function(){
		return {
			options: {
				'dateColumns': ['updated_at'],
				'headings': {
					'id': 'Id',
					'name': 'Name',
					'route': 'Route',
					'layout': 'Layout',
					'status': 'Status',
					'update_at': 'Last Updated',
				},
				'toMomentFormat': 'YYYY-MM-DDTHH:mm:ssZ',
			},
			columns: [
				'id',
				'name',
				'route',
				'layout',
				'status',
				'updated_at',
			],
			data: [
				{
					id: 1,
					name: "test",
					route: "test-route",
					layout: "standard",
					status: "live",
					updated_at: "2016-09-24T12:00:00+0100"
				}
			]
		}
	},
})
```

Here is the page html:
```
<!DOCTYPE html>
<html lang="en">
	<head>
	</head>
	<body id="app">

		<v-client-table class="card" elevation="1" :data="data" :columns="columns" :options="options"></v-client-table>

		<script src="/js/app.js"></script>

	</body>
</html>
```

If I load the `moment.js` script from a CDN before loading the bundled `app.js`, the script runs as expected without the error. However, this seems like a step back when I'm using browserify.

Is there a way to load moment.js so that it is bundled with browserify?

- Vue.js version: 1.0.26
- consumed using: browserify

**Comment by matfish2** [comment]
I deliberately avoided loading `moment` locally, in the `to-moment-format.js` scope, so as not to load unnecessary resources, for those who aren't using it, or already using it globally.
 
to require moment globally via browserify simply use 
`window.moment = require('moment')`
