### ISSUE TITLE
How to reset the page to the first page after generate a new table

### ISSUE THREAD

**Issue by nenya1840** [matfish2/vue-tables#109]
- Vue.js version: 1.0.21
- consumed using: webpack
- relevant code:
- steps for reproducing the issue: If you go to page 2, then generate a new table, the current page will stay on page 2 instead of going to its first page

**Comment by matfish2** [comment]
If by "generating a new table" you mean  programmatically inserting a new data set to an EXISTING table, then use `this.$refs.myTable.setPage(1)`

**Comment by nenya1840** [comment]
correct. What's the better way to do this? If I have some new data and an EXISTING table, and I want to replace the old data

**Comment by matfish2** [comment]
Already answered in my prev comment
