### ISSUE TITLE
v-server-table data is not sortable or filterable

### ISSUE THREAD

**Issue by vossavant** [matfish2/vue-tables#110]
- Vue.js version: 1.0.26
- consumed using: webpack
- FULL error message: n/a
- relevant code: see below
- steps for reproducing the issue: Create a new component with a server-side table, create an endpoint that serves up some JSON data, and add an "orderBy" option to the table's options object.

This is undoubtedly user error. The JSON data is properly formatted and is fetched OK, but the orderBy option is ignored. Typing in the "search query" filter box does nothing. From the network panel in the Chrome console, I can see the GET requests being sent with the proper query and orderBy params, but the data is not updated.

I tried `v-ref:table` as described in the docs and in [#37](https://github.com/matfish2/vue-tables/issues/37) but... there isn't enough information for me to figure out where to put ` this.$refs.table.refresh();` and it also doesn't seem like I want to programmatically refresh the data - shouldn't it happen automatically with each GET request?

I tried this with a client-side table, and sorting/filtering works as expected. My code:

**main.js**
```javascript
import Datatable from '../components/datatable.vue'
Vue.component('datatable', Datatable);

var VueTables = require('vue-tables');
Vue.use(require('vue-resource'));
Vue.use(VueTables.server, {});

new Vue({
	el: 'body'
});
```

**datatable.vue**
```html
<template>
    <div class="datatable-wrapper">
        <v-server-table url="path/to/local/json.php" :columns="columns" :options="options"></v-server-table>
    </div>
</template>

<script>
    export default {
        data: function () {
            return {
                columns: ['id', 'name', 'age'],
                options: {
                    orderBy: {
                        column: 'age'
                    }
                }
            }
        }
    }
</script>
```

**index.html**
```html
<datatable></datatable>
```

**Comment by matfish2** [comment]
As its name implies the server component doesn't handle any data manipulation itself. It merely sends the requested operations to the server, where the consumer - that would be you - is expected to handle the request and return the correct dataset, which is then displayed by the component.  Check out the example implementation that I've included for guidelines.
