### ISSUE TITLE
Reset VueTables

### ISSUE THREAD

**Issue by ibrahimkais** [matfish2/vue-tables#111]
- Vue.js version: v1.0.22
- consumed using: nuget
- VueTables.client

Well it is not an issue but i'm facing a scenario in which I need to reset the vuetables after a call back as the returned data is dynamic, I'm building the headings, columns and templates based on the returned data.
I have no problem with columns and headings or the data. I'm having a problem with templates which it should apply the new templates according to the returned data.

I don't know from where I can reset or restart or destroy and rebuild the vueTables.
I'll appreciate you help. thanks in advance.

**Comment by matfish2** [comment]
If i understand your question correctly you want to apply different templates to the same column based on some row data. This behavior can be achieved using template functions. E.G

name: function(row){
 If (row.x)
// return something
.
//return something else
}

**Comment by ibrahimkais** [comment]
I'm sorry I might not be clear. let me explain it in more details and code examples
my application has a widget that presents tabular data. the object schema of this data is dynamic I mean I return array of different object types every time I call that widget.

 you can see the result from [here ](https://1drv.ms/u/s!AhoI20bxam_9jStPTZUKiByDat1T)

![table](https://cloud.githubusercontent.com/assets/2798360/18886300/9985ee86-84ef-11e6-96ff-4158f8e8bd1a.JPG)

problem: first time calling is awesome. second is not. in the second still the table holds all the columns in the first call, I tried to reset the columns but it was no good.

what I need how can I reset the table every time I want to draw new data. and I have a problem with two way data binding. changes on values in the table is not reflected in my UiModel. 

to the code:
following the example of the client table on github, I added VueTables registeration like the following
 ```
 Vue.use(VueTables.client, {
                compileTemplates: true,
                skin: "table-striped table-bordered table-hover",
                perPage: 10,
                pagination: {
                    chunk: 10,
                    dropdown: false
                },
                orderBy: {
                    column: null,
                    ascending: false
                },
                sortable: []
            });
```

here is my html
```
 <div id="people" style="overflow:auto;">
        <v-client-table :data="tableData" :options="options" :columns="columns" v-if="loaded" v-ref:table></v-client-table>
    </div>
```

in the following function I call my back end service to return some data based on some criteria. receive the coming data apply some changes and prepare the table columns and templates  
```
 getSelectedRange(rangeObj: Range): void {
        this.m_backEndService.getDataRange(rangeObj).then((data: any[]) => {
            var uiModel = (<DetailsModel>this.m_model);
            uiModel.viewData.loaded = false;  //a flag for asynchronous looading setted with false and will be setted with true at the end of this function

//building the columns and templates for each column
                var max = rangeObj.endingColumn.charCodeAt(0); //return ASCII code at a specific position
                var min = rangeObj.startColumn.charCodeAt(0);     //return ASCII code at a specific position
                for (var i = min; min <= max; min++) {

//Each column will be a character ex. F,G,H,I and later these characters will be the properties of each row
                    uiModel.viewData.columns.push(String.fromCharCode(min));

//I'm using the following line to alert Vue that I added a new property so it add the observers on that object
//as it is an ECMAscript 5 error or bug. who cares !!
/////   http://012.vuejs.org/guide/best-practices.html#Adding_and_Deleting_Properties
                    Vue.set(uiModel.viewData.options.templates, String.fromCharCode(min), "<inpu type='number' value='{" + String.fromCharCode(min) + "}' number />");
                 }       

//preparing the data for the binding
            uiModel.viewData.rangeData.forEach((item) => {
                var objectData = {};
                for (var i = 0; i < uiModel.viewData.columns.length; i++) {
                    if (item.cells[i] && item.cells[i].value)
                        objectData[uiModel.viewData.columns[i]] = +item.cells[i].value.replace(",", "");
                }
                uiModel.viewData.tableData.push(objectData);
            });

            uiModel.viewData.loaded = true; //asynchronous looading flag
        });
    }
```

I hope the idea would be clearer now. thanks again

**Comment by matfish2** [comment]
Need to see you vue instance itself, and the way you apply the response from the backend.

I used a timeout to change an existing template and it worked. (Doesn't work when injecting a new template). 

https://jsfiddle.net/matfish2/f5h8xwgn/123/
