### ISSUE TITLE
warning: don't use v-if and v-for simultaneously

### ISSUE THREAD

**Issue by erikwestlund** [matfish2/vue-tables#112]
This issue is new for me.  Everything is still functional.  Just a console warning.

- Vue.js version: 1.0.28
- consumed using: (browserify/webpack/pre-compiled)    webpack
- FULL error message (including stack trace):

vue.common.js?4a36:1137[Vue warn]: <li v-for="page in pages" v-if="paginationStart + (page-1) <= totalPages">: Using v-if and v-for on the same element is not recommended - consider filtering the source Array instead. (found in component: <pagination>)warn @ vue.common.js?4a36:1137bind @ ?d41d:4114Directive._bind @ ?d41d:8489linkAndCapture @ ?d41d:7058compositeLinkFn @ ?d41d:7027Vue._compile @ ?d41d:8775Vue.$mount @ ?d41d:9610Vue._init @ ?d41d:2583Pagination @ VM721:2build @ ?d41d:5963mountComponent @ ?d41d:5880(anonymous function) @ ?d41d:5842(anonymous function) @ ?d41d:5860cb @ vue.common.js?4a36:367Vue._resolveComponent @ ?d41d:9033resolveComponent @ ?d41d:5862setComponent @ ?d41d:5841bind @ ?d41d:5801Directive._bind @ ?d41d:8489linkAndCapture @ ?d41d:7058compositeLinkFn @ ?d41d:7027Fragment @ ?d41d:3872FragmentFactory.create @ ?d41d:4089insert @ ?d41d:4757update @ ?d41d:4741Directive._bind @ ?d41d:8524linkAndCapture @ ?d41d:7058compositeLinkFn @ ?d41d:7027Vue._compile @ ?d41d:8775Vue.$mount @ ?d41d:9610Vue._init @ ?d41d:2583VServerTable @ VM729:2build @ ?d41d:5963mountComponent @ ?d41d:5880(anonymous function) @ ?d41d:5842(anonymous function) @ ?d41d:5860cb @ vue.common.js?4a36:367Vue._resolveComponent @ ?d41d:9033resolveComponent @ ?d41d:5862setComponent @ ?d41d:5841bind @ ?d41d:5801Directive._bind @ ?d41d:8489linkAndCapture @ ?d41d:7058compositeLinkFn @ ?d41d:7027Vue._compile @ ?d41d:8775Vue.$mount @ ?d41d:9610Vue._init @ ?d41d:2583VueComponent @ VM734:2build @ ?d41d:5963mountComponent @ ?d41d:5880(anonymous function) @ ?d41d:5842(anonymous function) @ ?d41d:5860cb @ vue.common.js?4a36:367Vue._resolveComponent @ ?d41d:9033resolveComponent @ ?d41d:5862setComponent @ ?d41d:5841bind @ ?d41d:5801Directive._bind @ ?d41d:8489linkAndCapture @ ?d41d:7058compositeLinkFn @ ?d41d:7027Vue._compile @ ?d41d:8775Vue.$mount @ ?d41d:9610Vue._init @ ?d41d:2583Vue @ ?d41d:9674(anonymous function) @ admin.js?d0ee:124(anonymous function) @ admin-5680c18805.js:1132__webpack_require__ @ admin-5680c18805.js:20(anonymous function) @ admin-5680c18805.js:64(anonymous function) @ admin-5680c18805.js:67

**Comment by mullet1989** [comment]
this issue has also just appeared for me in a production environment with browserify and minification - it doesn't affect the performance of the app to my knowledge though
