### ISSUE TITLE
Filters initial values

### ISSUE THREAD

**Issue by popozhu** [matfish2/vue-tables#113]
Hi, I have a problem when using the same key(eg: 'mykey') both in `options.params['mykey']` and `customFilters: ['mykey']` with these steps below: 
 - init the vuetable with `options.params = {'mykey': 'avlue'}`
 - the vuetable requets data from server side for the first time, only use the keys in  `options.params` 
 - after the first request,  when I click the next page in the bottom of this table, the value of `options.params['mykey']` is gone, the value is clear by the same key of `customFilters: ['mykey']`

As far as I can tell, after the first request, vuetable will call `initServerFilters` to init customFilters  **and I don't think this is needed here**, because `registerServerFilters` will do the same jobs in READY phase.

ref: 
 - https://github.com/matfish2/vue-tables/blob/master/lib/v-server-table.js#L66
 - https://github.com/matfish2/vue-tables/blob/master/lib/v-server-table.js#L84

I'm confused by these two functions, is there something I have missed?

**Comment by matfish2** [comment]
`Init-server-filters` is responsible for creating the initial array of `customQueries` when the plugin in ready.
`register-server-filters`, on the other hand, is registering the listeners and corresponding handlers for each of those queries.
So, I don't see any unnecessary duplication.

`params` should not receive the same key name as in `customFitlers`. 
The former is supposed to be used for immutable data, while the latter depends on user input.

**Comment by popozhu** [comment]
Thanks for your patience :)

Well, maybe it's better to make vue-tables compatible with this case...

In my case (`params` and `customFilters` have the same key), I have remove the `init-server-filters`, then it becomes:
 - the first time to request data from server, `getData` only use the key(s) in `params` and the default value(s) in `params`

 - no more `init-server-filters` after the first request, which will no more clear the value of the same key in `params` ( https://github.com/matfish2/vue-tables/blob/master/lib/methods/get-data.js#L14 )

 - in the later request without any customFilters event (just click the NEXT button below the table), the key and the value in `params` will be used again (which I expected)

 - also, when triggered by `customFilters` event with a new values,  vue-tables will `merge` the new value to the **SAME** key

**Comment by matfish2** [comment]
I am not entirely clear as to why you would need such a cumbersome solution. As I explained `params` and `customFilters` serve two distinct purposes and should not be confused. SInce both are sent along with the request it is important not to have naming overlap. 

If I understand correctly you are trying to give the filters an **initial value**. 
This is a feature I will probably implement in the near future, as a separate option which will address all filter types (generic filter, by column filters and custom filters) and allow the user to populate them in advance with an initial value other than an empty string.

**Comment by popozhu** [comment]
> If I understand correctly you are trying to give the filters an initial value.

YES!! You are right.

**Comment by matfish2** [comment]
I've added `filterInitialValues`. See Options API for usage.

**Comment by popozhu** [comment]
Great and so many thanks !!

Works as expected now.
