### ISSUE TITLE
will not refresh() data on empty table

### ISSUE THREAD

**Issue by mullet1989** [matfish2/vue-tables#114]
Hi, 

I am experiencing the same problem that is described in issue #90 - namely that calling refresh on a table with no data does not call the server. I have 3 tables in one page and editing the state of one record I want it to jump into the next table. This works fine when the tables are not-empty of course. Is there something that can be done?

Regards

**Comment by matfish2** [comment]
I think that problem was related to the pagination component, where 0 was not a legal page. I have changed the `totalPages` function to return at least 1.
Please pull the newest version and try again (It should pull `v-pagination` 0.1.1)

**Comment by mullet1989** [comment]
from my initial testing this look fixed, thanks for your prompt response @matfish2!
