### ISSUE TITLE
Sorting order

### ISSUE THREAD

**Issue by demetrius-edelin** [matfish2/vue-tables#117]
- Vue.js version: 1.*
- consumed using: webpack
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

Hello,

Your module helped me a lot in my project, however I have a small issue with the sorting order of the client table. On server everything is ok, as it keeps the DB sorting, but on client table it sorts the capital letters first and only then the small ones (and I need mixed, in alphabetical order). Can you tell me where is this sorting action done in the code to have a look if I can customize it for myself? I looked a lot, but I could not find it yet.

Thank you a lot,
Demetrius

**Comment by matfish2** [comment]
I am using vue's native `orderBy` filter.
http://v1.vuejs.org/api/#orderBy

**Comment by demetrius-edelin** [comment]
Thank you. I'll check it and maybe build a custom filter.

**Comment by demetrius-edelin** [comment]
If somebody else is asking it worked with a function in orderBy filter:

```
      sortCorrectOrder: function (a, b) {
          var column = this.orderBy.column;
          if (this.orderBy.ascending >= 0) {
              return a[column].toLowerCase() > b[column].toLowerCase();
          };
          return a[column].toLowerCase() < b[column].toLowerCase();
      }
```

and I used just the function:

orderBy sortCorrectOrder |
