### ISSUE TITLE
Functions as templates in the next version

### ISSUE THREAD

**Issue by VitruxPT** [matfish2/vue-tables#118]
@matfish2 In your latest commit you added a warning saying 

> using strings as templates is deprecated and will be removed in an upcoming release. Please use a function instead.

.
Can you please give me an example on how this would become a function and how would I be able to use it?

This is my actions template:
`actions: "<div class='pull-right' style='width: 100px;'><button type='button' class='btn btn-warning' href='javascript:void(0);' @click='$parent.EditCommand((" + '"{command}"' +"))'><i class='fa fa-pencil-square-o' aria-hidden='true'></i></button> <button type='button' class='btn btn-danger' href='javascript:void(0);' @click='$parent.DeleteCommand((" + '"{command}"' +"))'><i class='fa fa-trash-o' aria-hidden='true'></i></button></div>"`
Thanks

**Comment by matfish2** [comment]
Functions already exist, and were used alongside strings. 
See the Options API and the demo.

**Comment by VitruxPT** [comment]
@matfish2 I turned the template into a function but instead of getting the value that i want to retrieve (`command`) it's giving me only `$` instead.

My function:
`actions: function(row) {
                return "<div class='pull-right' style='width: 100px;'><button type='button' class='btn btn-warning' href='javascript:void(0);' @click='$parent.EditCommand((" + '"${row.command}"' +"))'><i class='fa fa-pencil-square-o' aria-hidden='true'></i></button> <button type='button' class='btn btn-danger' href='javascript:void(0);' @click='$parent.DeleteCommand((" + '"${row.command}"' +"))'><i class='fa fa-trash-o' aria-hidden='true'></i></button></div>"
            }`

**Comment by matfish2** [comment]
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals
