### ISSUE TITLE
Filter stops working when using highlightMatches with filterByColumn

### ISSUE THREAD

**Issue by joaokamun** [matfish2/vue-tables#119]
- Vue.js version: 
1.0.26
- consumed using: 
browserify
- FULL error message (including stack trace):
```
Uncaught SyntaxError: Invalid regular expression: /+/: Nothing to repeat
```
- relevant code:
- steps for reproducing the issue:

1. Activate **highlightMatches** and **filterByColumn** 
2. Try search for a **'+'**
3. Everything stop to work.

**Comment by matfish2** [comment]
Unable to reproduce. Please create a fiddle reproducing the bug.
