### ISSUE TITLE
Sort dates, if some dates are NULL

### ISSUE THREAD

**Issue by markcameron** [matfish2/vue-tables#120]
- Vue.js version: 1.0.28
- consumed using: browserify

When sorting a column that has dates, which have been parsed by moment, where some cells in the column contain a `null` date, they don't appear correctly in the date ordering. Often just Showing up randomly in the listing. Ideally they would show up on one end of the sort.

Is this an issue with the default Vue orderBy filter? Is it possible to set a custom filter?

You can reproduce the issue on your demo: https://jsfiddle.net/matfish2/f5h8xwgn/ by setting a couple of the `birth_date`'s to null. (It also seems to break the pager when you get to a page with the null date).

**Comment by matfish2** [comment]
A. The break results from the age calculation feature of the demo, which assumes a valid date and tries to run `fromNow` on `null`.
B. Other than that, yes, this is how vue's native orderBy filter behaves in the given circumstances.
Have a look at #117, who also had an issue with the native filter and wrote is own implementation.
This, however, requires a changes in the code itself (see there).
