### ISSUE TITLE
Q: Is it possible to call  own functions from customTemplate ?

### ISSUE THREAD

**Issue by m-behr** [matfish2/vue-tables#121]
- Vue.js version: 1.0.28
- consumed using: (browserify)

Hi there,
I use a custom template, nothing special, just a fixed column for instant access eg:
```html
<thead>
<!-- vue-tables default stuff -->
<th>Actions</th>
</tr>
</thead>

<!-- vue-tables default stuff -->
<td><button @click="deleteItem(row.id)">delete</button></td>
</tr>
```
but I see no way to call 'deleteItem' on my instance:

```js
Vue.use(VueTables.server, {}, {template: require('../../../../../resources/assets/js/index-table.html')});

import {destroyModel} from '../../../../../resources/assets/js/vuex/modelActions'

var vm = new Vue({

    el: '#my-index',
    components: {},

    data: {
        url: '/api/entries',
        columns: ['id', 'name'],
        options: { },
    },
    methods: {
            deleteItem(id) {
                console.log(id)
                // this.destroyModel(id)
            }
    },
    vuex: {
        actions: {
            destroyModel
        }
    }
})
```

the only 'way to go' seems via options.deleteItem, but inside options, the vuex stuff is not visible.

Did i miss something / made a mistake ? 

Thanks in advance
Michael

**Comment by matfish2** [comment]
You need to call the parent instance:

`<td><button @click="$parent.deleteItem(row.id)">delete</button></td>`

**Comment by m-behr** [comment]
Thank you, but I am sorry, that does not work:
```Uncaught TypeError: scope.$parent.deleteItem is not a function(…)```

**Comment by matfish2** [comment]
Then it's probably not a direct parent. Just follow the components tree.

**Comment by m-behr** [comment]
$parent.$parent did the trick. Thank you!
