### ISSUE TITLE
Cannot read property 'scope' of undefined

### ISSUE THREAD

**Issue by egnsh93** [matfish2/vue-tables#122]
Hey there, I am receiving an error after registering the VueTable Client component, here is some preliminary information about my setup:
- Vue.js version: 1.0.26
- laravel-elixir: 6.0.0-0-9
- laravel-elixir-vue: ^0.1.4
- laravel-elixir-webpack-official: ^1.0.2
- Consumed using: webpack
- Error message (including stack trace): http://kopy.io/tNiGc
- Relevant code: http://kopy.io/QmiUz
- Steps for reproducing the issue: register the component as usual, then compile with gulp

When I inspect the component with Vue Devtools I can see that it is registered and I can even view the contents of the table / objects / etc however the component does not display in the DOM or on the page. In the end this component will be nested, however I just want to get it working out of box.

Any help would be appreciated

**Comment by matfish2** [comment]
Unfortunately I can't see any problem with your code, and am unable to reproduce this issue. I will leave it open in case anyone else encounters a similar issue or knows how to fix it.
