### ISSUE TITLE
How to disable pagination component

### ISSUE THREAD

**Issue by SterileSummer** [matfish2/vue-tables#128]
Is there any options or something?
I've read [VueTables Options API](https://jsfiddle.net/matfish2/bp1g4khr/embedded/result/) but found nothing
Thanks.

**Comment by matfish2** [comment]
Why would you want to disable the pagination? How would the user paginate?
If you meant you want to display all the records in one page regardless of the number of records, you can use the `perPage` and `perPageValues` options for this.
