### ISSUE TITLE
Q: Custom columns should not be show if not defined in columns attribute?

### ISSUE THREAD

**Issue by san4io** [matfish2/vue-tables#133]
- 1.16:
- consumed using: (browserify)

I have set default options for VueTables 
```
Vue.use(VueTables.server, {templates: {
    edit: function (row) {
        return `<a class="btn btn-sm btn-default" href="#/${row.id}/edit"><i class='fa fa-edit'></i></a>`
    },
    remove: function (row) {
        return `<a class="btn btn-sm btn-danger" href="#/${row.id}/edit"><i class='fa fa-remove'></i></a>`
    }
}});
```

And in every component they appear even if they're not listed in columns attribute. Is there a possibility not to show them if they're not in columns array, using your default component without modifying it?

![image](https://cloud.githubusercontent.com/assets/12079341/23827987/493b36bc-06cb-11e7-82d5-bc351c8166f3.png)

And one more question is there a possibility to modify this part:
![image](https://cloud.githubusercontent.com/assets/12079341/23827999/b1f08cf2-06cb-11e7-82e1-3277ecacc3dd.png)

To add custom buttons in right side? like new entry button?

Thanks in advance!

**Comment by matfish2** [comment]
Custom columns are merged into the columns array. If you don't want them to appear in all components you need to define them on the instance level, not the component level, i.e not in `Vue.use` but through the `options` prop.

As for the other question, you can modify the template as documented:

```js
Vue.use(VueTables.client, {}, { template: require('./my-template.html') });
```
