### ISSUE TITLE
Laravel Implementation

### ISSUE THREAD

**Issue by ServerJunge** [matfish2/vue-tables#134]
- Vue.js version: 2
- consumed using: webpack

Hello,

at first I want to say thank you for your plugin! I am new to coding but I hope you can help me.

My backend is Laravel 5.4. The setup of your plugins works fine.

At first my code.

This is the script part of my component.
```
<script>
    export default {
        data() {
            return {
                columns: ['id', 'name'],
                users: null
            }
        },
        mounted() {
            axios.get('/api/getAllUsers')
                    .then(response => {
                        this.users = response.data
                        console.log(response.data)
                    });
        }
    }
</script>
```

And this is the part in my component

```
<div class="block-content">
            <v-client-table :data="users" :columns="columns"></v-client-table>
</div>
```

I get the following error:

```
[Vue warn]: Invalid prop: type check failed for prop "data". Expected Array, got Null. 
(found in <ClientTable>)
```

I think that the response from my api call has the wrong format.

This is my Laravel Controller part for the api call.

```
public function getAllUsers()
    {
        $users = User::all();
        return $users;
    }
```

I saw that there is an [Eloquent implementation](https://github.com/matfish2/vue-tables/tree/master/server/PHP)

But I don't know how to use it. Can you explain it? 

When I use your example data structure every works fine.

```
columns:['id','name','age'],
    users: [
      {id:1, name:"John",age:"20"},
      {id:2, name:"Jane",age:"24"},
      {id:3, name:"Susan",age:"16"},
      {id:4, name:"Chris",age:"55"},
      {id:5, name:"Dan",age:"40"}
    ],
```

I hope you understand what i mean and thanks again for your great work!

**Comment by matfish2** [comment]
Since you are loading the data asynchronously `users` is still `null` when the component is mounted. In order to halt the rendering until the data is assigned, you need to add a `v-if` conditional to the component:

```html
     <v-client-table :data="users" :columns="columns" v-if="ready"></v-client-table>
```

```js
<script>
    export default {
        data() {
            return {
                columns: ['id', 'name'],
                users: null,
                ready: false
            }
        },
        mounted() {
            axios.get('/api/getAllUsers')
                    .then(response => {
                        this.users = response.data;
                        this.ready = true;
                        console.log(response.data)
                    });
        }
    }
</script>
```
