### ISSUE TITLE
Date format from server

### ISSUE THREAD

**Issue by jsodeman** [matfish2/vue-tables#138]
I'm using the server version of the control and the API is passing dates back in a format like {Created: "2016-08-18T00:00:00", other data...}

I'd like to display the date as MM/DD/YYYY and be able to order by it. I don't need filtering.

Currently I've tried this but it's not working

```
import moment from "moment";
window.moment = moment;

options: {
	toMomentFormat: "MM/DD/YYYY",
	dateFormat: "MM/DD/YYYY",
	dateColumns: ["Created"],
},
```

**Comment by matfish2** [comment]
A for presentation you can either return the desired format from the server, or use the `templates` option to alter it using moment:

```js
{
dateColumns:['Created'], // this will show the daterangepicker in case you are using a per column filter
templates:{
   Created: function(row) {
      return moment(row.Created).format('MM-DD-YYYY');
   }
}
}
```

As for sorting it is entirely up to you to implement it on the server side. The server component is only sending the request params.

**Comment by vhpm18** [comment]
formattedDate(created_at) {
            Moment.locale('es');
            return Moment(created_at).format('LL');
        }
