### ISSUE TITLE
failed to run the server version with java backend. seems [Vue warn]: Unknown custom element: <v-server-table> - did you register the component correctly?

### ISSUE THREAD

**Issue by openwsn** [matfish2/vue-tables#14]
failed to run the server version with java backend. 
[Vue warn]: Unknown custom element: <v-server-table> - did you register the component correctly?

ps1: The current live demo of the server version failed to show the data too. Suggest to give a packed version just like vue-tables.min.js.

**Comment by matfish2** [comment]
A. This is a JS Package, and as such it is server-agnostic. As Vue notifies the problem seems to be that the component was not registered. Did you remember to call `Vue.use(VueTables.server)`?

B. What browser did you use to view the server demo? Didn't understand your suggestion

**Comment by zeeshanyshaikh** [comment]
It's showing the same error for me. I am using Laravel and Webpack. Below is my settings

> resources/assets/js/app.js
```javascript
window.Vue = require('vue');
import {ServerTable, ClientTable, Event} from 'vue-tables-2';

Vue.use(ServerTable, {}, false, require('../vuetable/compiled/v-server-table.js')('server'));
```
I have copied the "complied" folder and placed in my resource/assets directory under folder "vuetable"
i tried both lines of code, but both failed
> Vue.use(ServerTable, {}, false, require('../vuetable/compiled/v-server-table.js')('server'));

>Vue.use(ServerTable, {}, false, require('../vuetable/compiled/template.js')('server'));



> index.blade.php
```html
<div class="box-body">
    <v-server-table url="{{ route('users.data') }}" :columns="columns" :options="options" name='serverTable'></v-server-table>
</div>
```

> Error Message

[Vue warn]: Unknown custom element: < v-server-table > - did you register the component correctly? For recursive components, make sure to provide the "name" option.
