### ISSUE TITLE
dateformate and server table

### ISSUE THREAD

**Issue by sylvaincaillot** [matfish2/vue-tables#141]
Hi, 
My API is returning dates in the following format: '1997-01-20T00:00:00'.
I tried to play vue-tables-2 to get '20-Jan-1997' instead but didn't get any success.
I tried the following:
```
...,
dateFormat: 'DD-MMM-YYYY',
dateColumns: ['departureDate', 'returnDate'],
...
```
Could you please give me some directions on the way to format dates for v-server-table?

Thank you very much

Sylvain

**Comment by matfish2** [comment]
You can either format the date on the server-side, or else use the templates option to reformat:

```js
templates:{
 returnDate: function(row) {
   return moment(row.returnDate).format('DD-MM-YYYY');
}
}
```
