### ISSUE TITLE
V-Server-Table (vuetables2)

### ISSUE THREAD

**Issue by pratikshah99** [matfish2/vue-tables#144]
Hi,
i am new with vue js
i implement v-client-table and it's working, but when i implement v-server-table at that time i got error
data.json() is not a function.
Please suggest api code and full demo.

My API Or service code is like : 
/items this url call service like
public function getData()
{
$items = Item::paginate(15);
return
 [
            'data'  => $items,
            'count' => 6,
        ];
}
And where i call that is .vue file
 <v-server-table url="/items" :columns="columns" :options="options" name='serverTable'>

  </v-server-table>

Please, solve i can't understand where is my mistake

**Comment by matfish2** [comment]
Wrong repo. Open in vue-tables-2
