### ISSUE TITLE
Check for data.length redundant?

### ISSUE THREAD

**Issue by Adgek** [matfish2/vue-tables#17]
In my code i am often trying to load a table that might have no data in it. I was hoping to get the noResults message of "No matching records" instead of my js returning. By commenting out this section here in v-client-table.js create method
      // if (!this.data.length) {
      //     console.error("v-client-table: the data array must have at least one row object.");
      //     return;
      // }
It seems to have the wanted effect of telling me that i have no matching records. Leads me to believe that you already handle this issue. Might be totally mistaken here though.

**Comment by matfish2** [comment]
You are right. I will fix it soon. Thank you.

**Comment by Adgek** [comment]
Awesome thanks :)
