### ISSUE TITLE
null values in data

### ISSUE THREAD

**Issue by nuklehed** [matfish2/vue-tables#18]
When my data set has null values I am getting an isValid exception. I've traced it back to the is-valid-moment-object helper: 

`module.exports = function(val) {
  return typeof val.isValid=='function' && val.isValid();
}`

My hack was to add (null!==val) to the return:

`return (null!==val) && typeof val.isValid=='function' && val.isValid();`

Use the jsfiddle to recreate the issue. Simply change one of tableData's property values to null and run:[jsfiddle](https://jsfiddle.net/matfish2/f5h8xwgn/)

Could be a better way to address this, but without change how my app returns data, this was the simplest method. Anxious to hear any feedback.

Thanks!

**Comment by matfish2** [comment]
Thanks. Fixed it.

**Comment by nuklehed** [comment]
Awesome tool. Glad I could help!

Ernest Carroll
215 534 1876
