### ISSUE TITLE
How to filter by number range?

### ISSUE THREAD

**Issue by PascalAnimateur** [matfish2/vue-tables#19]
How would I go about implementing a range filter for columns containing number values?

**Comment by matfish2** [comment]
You'll need to fork the repo and add the functionality.

General Guidelines:

1. add a numericColumns option to config/defaults.js, similar to the dateColumns existing one
2. add the filter template to table-template.html and display it conditionally using v-if
3. alter filters/search.js to handle these columns

If you do so and like the outcome you are welcome to send a PR
