### ISSUE TITLE
Live example

### ISSUE THREAD

**Issue by PrimozRome** [matfish2/vue-tables#21]
Is there a live example of this component to bi viewed anywhere? I am looking for a good server side table component for VueJS and this is by much the only one I have found. Is this project obsolete or still active?

**Comment by matfish2** [comment]
The server side example doesn't currently have a live a example (I will remove the broken link).
This project is active.

**Comment by jauharfuadi54** [comment]
> The server side example doesn't currently have a live a example (I will remove the broken link).
> This project is active.

Why?
