### ISSUE TITLE
Usage with webpack

### ISSUE THREAD

**Issue by PrimozRome** [matfish2/vue-tables#23]
Did you use this with webpack maybe? Seems to be a problem... I am getting this error:

```
./~/vue-tables/lib/table-template.html
Module parse failed: /Users/primozrome/Documents/Web/webshop-frontend/node_modules/vue-tables/lib/table-template.html Line 1: Unexpected token <
You may need an appropriate loader to handle this file type.
| <div class="VueTables VueTables--[[source]]">
|   <div class="row">
|     <div class="col-md-6">
 @ ./~/vue-tables/lib/helpers/generate-table-html.js 3:17-50
```

**Comment by PrimozRome** [comment]
I have installed html-loader and added this to the webpack configuration file

`
      {
        test: /\.html$/,
        loader: 'html'
      }
`

**Comment by matfish2** [comment]
Indeed, did is the equivalent of `browserify`'s `stringify` transform

**Comment by decebal** [comment]
try vue-html loader; worked for me

**Comment by bvelastegui** [comment]
**Tanks** @decebal this works

**Comment by mohamed-ibrahem** [comment]
how can i solve this with laravel elixir?
