### ISSUE TITLE
plugin.apply is not a function

### ISSUE THREAD

**Issue by nacr-dev** [matfish2/vue-tables#24]
I'm getting this error while using the vue-tables package any help?

**Comment by matfish2** [comment]
Are you using daterangepicker? 
I think you are using an outdated version of it, where the `apply` event didn't exist.
Be sure to use the latest version.

**Comment by nacr-dev** [comment]
Hi I'm using vue.js with laravel/elixer and browserify.

The only part of the docs I do is this.
var VueTables = require('vue-tables'); on my app.js file.

Afther that I get the error and all my vue.js stops to work.

What details can a give to help you?

Tks

**Comment by matfish2** [comment]
Did you install the package normally using `npm install`?

**Comment by nacr-dev** [comment]
Yes I used npm install and its a run-time error.

**Comment by matfish2** [comment]
What versions of Vue.js and laravel are you using?

**Comment by nacr-dev** [comment]
Laravel 5.2 and Vue.js 1.0.20

**Comment by matfish2** [comment]
Can you post the complete error stack

**Comment by matfish2** [comment]
I've managed to recreate the error by calling `Vue.use(VueTables)` instead of `Vue.use(VueTables.client) or Vue.use(VueTables.server)`. Is that possibly the case?

**Comment by nacr-dev** [comment]
oh, sorry for the time. let me check.

**Comment by nacr-dev** [comment]
oh face palm for me! Sorry for your time no error now.

**Comment by matfish2** [comment]
It's ok. Glad I could help  :)

**Comment by nacr-dev** [comment]
tks m8 I will close this since theres no issue.
