### ISSUE TITLE
This is a Question not a Issue:

### ISSUE THREAD

**Issue by nacr-dev** [matfish2/vue-tables#25]
Hello,

I'm reading the docs and I can see a way in client-side to force a new http request according to the page we are on and the number of records per page.

Is this functionality in place? or is there a event we could hock to?

Tks

**Comment by matfish2** [comment]
I don't understand the scenario in which you would need the client-side component to make http requests. Why not use the server-side component?

**Comment by nacr-dev** [comment]
ok will check that sorry.
