### ISSUE TITLE
Request: Eloquent implementation Demo

### ISSUE THREAD

**Issue by nacr-dev** [matfish2/vue-tables#27]
Hello is it possible to have a Eloquent implementation demo available?

Tks

**Comment by matfish2** [comment]
Using the class is pretty straight forward:
A. include the class and interface in your project under some folder (say 'DataTables')
B. namespace them accordingly.
C. Declare a route whose url you will pass to the `url` property on `v-server-table`
D. in the controller handling the request:

```
$model = new Post;
$columns = ['id','title', 'body', 'author'];

return new (EloquentDataTables())->get($model, $columns);
```

**Comment by nacr-dev** [comment]
ok I will five it a go and give feed back.
