### ISSUE TITLE
Daterangepicker not sorting

### ISSUE THREAD

**Issue by Melcus** [matfish2/vue-tables#28]
The daterangepicker (http://www.daterangepicker.com/) is not sorting at all. No matter what interval I set, the records won't display. The field is being parsed with carbon to return in needed format

```
public function getFootageDateAttribute($date)
{
    return Carbon::parse($date)->format('d-m-Y');
}
```

also tried with `return Carbon::parse($date)->toAtomString();`
In the js file, I have `dateFormat: "DD-MM-YY", filterByColumn: true, dateColumns: ['footage_date'], . When I inspect with vue dev-tools, the field is footage_date: "03-04-2016"`

If I hardcode the date as in the example ( https://jsfiddle.net/matfish2/f5h8xwgn/ ) using

```
// Courtesy of Tomasz Nurkiewicz (Elegant method to generate array of random dates within two dates)

function randomDate(start, end) {
  return moment(start.getTime() + Math.random() * (end.getTime() - start.getTime()));
}
```
the date is in this format `footage_date: "1974-03-27T18:19:40.364Z"` and it works.

Pastebin full js file http://pastebin.com/mS8xpd0n
Client side : http://pastebin.com/xTUcAK98

**Comment by matfish2** [comment]
You need to pass the dates as moment objects, not as strings.

**Comment by Melcus** [comment]
Is there a way to mutate a date string into a moment object ?

**Comment by matfish2** [comment]
Not on the server-side of course.
On the client-side, have a look at moment's docs to see how to instatiate a moment object from a string with a given format: 
http://momentjs.com/docs/#/parsing/string-format/

In the future, I might add an option to pass strings to columns marked as date columns, and create moment objects out of them.

**Comment by Melcus** [comment]
> In the future, I might add an option to pass strings to columns marked as date columns, and have the component create moment objects out of them.

Yes please :+1:
