### ISSUE TITLE
Server side. Search request 2 times

### ISSUE THREAD

**Issue by HenoTaMyJIb** [matfish2/vue-tables#29]
Hello,

- Vue.js version: 1.0.20

When filtering results, request to the server is made 2 times with the same request parameters.

Code
```javascript
Vue.use(VueTables.server, {
    compileTemplates: true,
  }
);

new Vue({
  el: '#content',
  options: {
      delay: 500,
      columns:['title','artist', 'album'],
      headings: {
        name: 'Title',
        birth_date: 'Artist',
        age: 'Album',
        edit: 'Edit',
        delete: 'Delete'
      },
      templates: {
        edit: '<button \
              @click="$parent.load({id})" \
              class="btn btn-primary btn-sm mr10">\
                <i v-if="!$parent.loading" class="glyphicon glyphicon-edit"></i>\
                <i v-else class="fa fa fa-spin fa-spinner"></i>\
              </button>',
        delete: "<a href='javascript:void(0);' ><i class='glyphicon glyphicon-erase'></i></a>"
      },
      filterByColumn: false,
      sortable: ['id']
    }
});
```

**Comment by matfish2** [comment]
Please try now. Let me know if there is still a problem

**Comment by HenoTaMyJIb** [comment]
Thank you! Everything works properly.

One question:
Same table, where filterByColumn: false, but there is also a row of alphabet letters, each letter has a click event. On click, server returns results, where first letter of name is clicked letter. 
The only problem is, that "Filter Results" box has text [object Object].
Is there a way to left this box empty? Or maybe another way to resolve this?

Method code.
```
search: function(query) {
   var VueTable = this.$children[10];
   VueTable.query = {name : query};
   VueTable.refresh();
}
```

**Comment by matfish2** [comment]
Well, this is to be expected. When `filterByColumn` is set to `false` (which is the default) The `query` property is a string, not an object. Forcing it to be an object results in a string representation of this object: `[object Object]`.

Since the `query` property has two-way binding to the input field using `v-model`, I don't see an immediate solution for suppressing the value from being presented inside it.

**Comment by HenoTaMyJIb** [comment]
Okay. Thank you very much.

**Comment by matfish2** [comment]
I've added a `customFilters` option for both client and server side components. You might want to check it out.

**Comment by HenoTaMyJIb** [comment]
Excellent! Thank you for your work and effort.
