### ISSUE TITLE
X time ago sorting as string instead of moment

### ISSUE THREAD

**Issue by Melcus** [matfish2/vue-tables#30]
The created_at attribute is being passed as a moment object, but it's being parsed as string.

http://i.imgur.com/41xOvDO.png

```
 ready: function(){
        this.$http.get('/api/footage')
            .then(function(response){
                footages = response.data
                footages.forEach(footage => {
                        footage.created_at = moment(footage.created_at).fromNow()
                })
                this.tableData = footages
            }.bind(this))
    },
```

Also, how do I set Added to sort by default descending? Thanks in advance

**Comment by matfish2** [comment]
A. You are NOT passing moment objects but rather a string, by calling `fromNow`. 
The plugin currently supports only absolute date formatting (see the `dateFormat` option). I may add relative formatting in the future. 
B. use the `orderBy` option. See the options API.
