### ISSUE TITLE
[Client-side] Column gets duplicated when is set asynchronously

### ISSUE THREAD

**Issue by nikolassilva** [matfish2/vue-tables#31]
When the table data is initialized as an empty array and it has `templates` and `columns` defined in `options`, templated columns gets duplicated.

This occurs because you set `this.customColumns` by differing the `this.templatesKeys` from `this.allColumns`. But what if the table data isn't filled yet? It gets duplicated cause `this.allColumns` doesn't have any key.

You can reproduce this with the following code:

```js
var vm = new Vue({
  el: '#app',
  data: {
    options: {
      columns: ['foo'],
      templates: {
        foo: function(row) {
          return "<h1>" + row.foo + "</h1>";
        },
      }
    },

    data: [],
  }
});

setTimeout(function() {
  vm.$set('data', [{ foo: 'bar' }]);
}, 1000);
```

Btw cool vue component, thank you!

**Comment by matfish2** [comment]
This type of async loading problems can be solved by adding a `v-if` to the component along with some `loaded` flag.

**Comment by matfish2** [comment]
In any case, you are right. the diff should be applied to the this.queryable and not this.allColumns. Fixed it.

**Comment by nikolassilva** [comment]
Thanks! :+1:
