### ISSUE TITLE
Option to add track-by="$index" in client tables

### ISSUE THREAD

**Issue by johnie** [matfish2/vue-tables#33]
- Vue.js version: `^1.0.18`
- consumed using: (webpack)
- relevant code:
`trackBy:'track-by="$index"'`
`Line 18: File v-client-table.js`

**Comment by matfish2** [comment]
Good idea. I have added a 'trackBy' option. Default is `$index`

**Comment by johnie** [comment]
Perfect!

Skickat från min iPhone
