### ISSUE TITLE
Being able to append module template to templates

### ISSUE THREAD

**Issue by johnie** [matfish2/vue-tables#34]
- Vue.js version: `^1.0.21`
- consumed using: (webpack)

It would be nice if you could include a template via a module within the template key, instead of pure strings.

- relevant code:
```
<template>
      <v-client-table :data="tableData" :columns="columns" :options="options"></v-client-table>
</template>

<script>
import Modal from './Modal'
export default {
  components: {
    Modal
  },
  data () {
    return {
      columns: [],
      tableData: [],
      options: {
        templates: {
          // See here
          operations: Modal
        }
      }
    }
  }
}
</script>
```

**./Modal.vue**
```
<template>
  <a href="#" @:click.prevent="show = !show">Edit</a>
  <div v-show="show">
    <h1>Modal</h1>
  </div>
</template>

<script>
  export default {
    data () {
      return {
        show: false
      }
    }
  }
</script>
```

**Comment by matfish2** [comment]
Why not extract a component and use in the `templates`?

```
{
 templates: {
operations: "<modal some-prop="{some_column}></modal>"
}
```

**Comment by johnie** [comment]
@matfish2 But that for some reason doesn't work. It won't output any HTML

**Comment by matfish2** [comment]
You probably registered the component locally on your instance, and so the table instance, which is a child, cannot access it. 
Anyway, it is not a good idea to repeat the modal for each row. Instead use a link only as the template and client-side routing (vue-router) to load the modal.

**Comment by johnie** [comment]
@matfish2 You're right!

**Comment by matfish2** [comment]
Glad I could help.
