### ISSUE TITLE
Leave Glyphicons/Font Awesome up to developer

### ISSUE THREAD

**Issue by nbyloff** [matfish2/vue-tables#35]
I am playing with vue-tables, and everything is working just fine except our project uses font awesome with bootstrap instead of glyphicons.

Giving the user the option to change the font package would be nice. I tried to simply do this in a less file, but that didn't work.

```javascript
.glyphicon:extend(.fa) {};

.glyphicon-chevron-up:extend(.fa-chevron-up) {};
.glyphicon-chevron-down:extend(.fa-chevron-down) {};
```

**Comment by matfish2** [comment]
I am away for 10 days. Will add it when I'm back.

**Comment by ClevonNoel** [comment]
Got this to work with my sass project

**Comment by matfish2** [comment]
I've added a new `sortIcon` option. See Options API

**Comment by nbyloff** [comment]
Perfect thanks!
