### ISSUE TITLE
How to trigger reload of data using v-server-table?

### ISSUE THREAD

**Issue by ClevonNoel** [matfish2/vue-tables#37]
How do one go about reloading vue-table from parent

**Comment by matfish2** [comment]
Assign a v-ref to the table, fetch it using this.$refs, and call the
refresh() method on it

**Comment by erikwestlund** [comment]
Can you expand on this matfish2?

I am able to set a`v-ref` on the table.  Then I click a button, it sends parent a message to run a method.  I run this code in the method:

`this.$refs.file_manager.refresh()`

where `file_manager` is the v-ref on the server table

that returns: 

`Uncaught TypeError: this.$refs.file_manager.refresh is not a function`

Any ideas?

**Comment by ixperiencenl** [comment]
@matfish2 maybe put this in the options description because this is something used a lot I think. Was searching for this quite a while...

**Comment by matfish2** [comment]
This is not an option. It is a method, which is documented in the `methods` section of the readme.
