### ISSUE TITLE
Sorting works only for one column / Date

### ISSUE THREAD

**Issue by lukpep** [matfish2/vue-tables#40]
vue: 1.0.7
vue-tables: 1.4.14
webpack

component: http://pastebin.pl/view/9078880b

sorting works just for "Ilość" column
Video: https://vimeo.com/165673453
pass: tables

**Comment by matfish2** [comment]
I think you are using illegal column names. A property cannot have a space as far a I know. Use an underscore instead.

**Comment by lukpep** [comment]
@matfish2 - it could be true. But right know my web API serves data in that way - with spaces in json params names. Is it possible to somehow workaround it without touching the backend?

**Comment by matfish2** [comment]
Well, I'm using vue's native `orderBy` filter, simply passing the variable, so I'm not sure if there is a workaround I can implement.

**Comment by matfish2** [comment]
I guess you can also iterate over the returned data and replace the keys on the client side before assigning the data to the table.

**Comment by lukpep** [comment]
from http://stackoverflow.com/questions/33855393/javascript-object-keys-with-spaces

http://stackoverflow.com/a/33860675/4402261 <- maybe this small change in vue-tables can help?

**Comment by matfish2** [comment]
I tried replacing the dot notation with brackets as suggested, but my tests are failing.

**Comment by lukpep** [comment]
@matfish2 it's my first ever approach to java script, to vue.js and to anything related to html / web aps - so I propably pass on that - not my level yet ;)
I've rebuilded my database - all fields now have underscores instead of spaces and it works fine. 
Thank You :)

PS. I have some question about templates - should I ask it here or start new issue?

**Comment by matfish2** [comment]
You can ask here

**Comment by lukpep** [comment]
`'Data': function(row) {
          var date = new Date(row['Data'].$date);
          return GetDateString(date);
        },

works fine. But when I try:
`'Data':"{Data,$date}"` a just get string {Data,$date} instead of time object (epoch style long digit)

**Comment by matfish2** [comment]
A. When a template is passed as a string, the curly brackets should contain one of the properties in the dataset. If no match is found the string returns as it is. Clearly `{Data, $date}` doesn't match any property.
 
B. Dates should be passed as `moment` objects, not plain JS Date objects. The `toMomentFormat` option allows you to pass a format matching the one in your dataset (say 'YYYY-MM-DD'), and converts the dates for you.

**Comment by lukpep** [comment]
I added:
`toMomentFormat: true,
      dateColumns: ['Data'],
      dateFormat: 'YYYY-MM-DD',`

and i get:
`build.js:59713 Uncaught ReferenceError: $ is not defined(anonymous function) @ build.js:59713module.exports @ build.js:59712(anonymous function) @ build.js:8420client.ready @ build.js:59203Vue._callHook @ build.js:16303ready @ build.js:17531on @ build.js:17328Vue.$emit @ build.js:17409Vue._callHook @ build.js:16306attach @ build.js:12032Fragment.callHook @ build.js:11911multiBefore @ build.js:11963insert @ build.js:12736update @ build.js:12719_update @ build.js:16405Watcher.run @ build.js:11483runBatcherQueue @ build.js:11211flushBatcherQueue @ build.js:11187nextTickHandler @ build.js:8642
backend.js:1 [vue-devtools] Ready. Detected Vue v1.0.21`

- problematic line is: `dateColumns: ['Data'],`

**Comment by matfish2** [comment]
A. date columns have a unique range filter using `daterangepicker`, which itself depends on `jquery` ($) and `moment`. If you wish to use this filter use need to import the dependencies.
Also `toMomentFormat` accepts a string - moment format -  NOT a boolean.
`dateFormat` accepts the format you want to use to present the moment object.

If you don't want to the unique filter you can omit the `toMomentFormat` and `dateColumns` options, and manually create the moment objects, iterating over the response (which is exactly what `toMomentFormat` does behind the scenes).
