### ISSUE TITLE
using components in templates

### ISSUE THREAD

**Issue by lukpep** [matfish2/vue-tables#41]
Is it possible to use for example tooltip from vue-strap in template?

`<tooltip placement='bottom' content='test'><a><i class='glyphicon glyphicon-th-list'></i></a></tooltip>`

works like charm outside vue-tables.
But when I use it in template:
`'Proces': "<tooltip placement='bottom' content='dupa dupa dupa'><a><i class='glyphicon glyphicon-th-list'></i></a></tooltip>"`

I get: build.js:9218 [Vue warn]: Unknown custom element: <tooltip> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by matfish2** [comment]
You probably registered the component locally on your instance, and so the table instance, which is a child, cannot access it. You need to register it globally.
