### ISSUE TITLE
Reactive data client side

### ISSUE THREAD

**Issue by cloud9business** [matfish2/vue-tables#42]
- Vue.js version:
- consumed using: (browserify)
- FULL error message (including stack trace): N/A
- relevant code:
```
<v-client-table :data="tableData" :columns="columns" :options="options"></v-client-table>
```
```
module.exports = {
    props: ['user', 'itemCategories'],


    /**
     * The component's data.
     */
    data() {
    return {
        columns: ['name', 'default_markup'],
...
        tableData: this.itemCategories,
```
Using the client side version of vue-tables, is it possible to make the tableData reactive? So when I add a new item to itemCategories using a form on the same page the item automatically appears in the visualised table.

**Comment by matfish2** [comment]
Vue data is reactive by nature. This should work out of the box. If it doesn't maybe you should assign `itemCategories` directly to `v-client-table`, which is a child component if I understand correctly, and skip the `tableData` middleman.

**Comment by Alaurent333** [comment]
I have a similar problem.
`  <v-client-table :data="listeCnts" :columns="columns" :options="options"> </v-client-table>`

In my app, i use a REST API for change the data of  listeCnts: 
```
Vue.use(VueTables.client, {filterByColumn: true});

new Vue({
  el: "#app",
  data: {
    listeCnts: [ 
      { id:1, numcnt : '5748', reg:'NE' },
      { id:2, numcnt : '4875', reg:'OU' },
    ],
    columns:['id','numcnt','reg'],
    options: {},
   },
   methods: {
      recup: function () {
          this.$http.jsonp('http://localhost:8080/').then(function(res){
              this.listeCnts=JSON.stringify(res.data)
          }); 
      }
  }
});
```
If i print listeCnts values after the call of recup function. I can see the values of listCnts had change but not my table.

**Comment by matfish2** [comment]
You need to bind `this`, so it will refer to your Vue instance:

this.$http.jsonp('http://localhost:8080/').then(function(res){
              this.listeCnts=JSON.stringify(res.data)
          }.bind(this));
