### ISSUE TITLE
Can't use <v-server-table>, getting errors

### ISSUE THREAD

**Issue by jpmurray** [matfish2/vue-tables#44]
- Vue.js version: 1.0.21
- consumed using: browserify
- steps for reproducing the issue: adding the said tag
__

Hello,

I've used your client-side example perfectly, although I want to use your server-side with eloquent. Changing the `<v-client-side>` tag for `<v-server-table>` gives me this error:

> Unknown custom element: <v-server-table> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

**Comment by matfish2** [comment]
As the error implies  you need to register the server component. 
'Vue.use(VueTables.server)'
