### ISSUE TITLE
Refresh method is undfined

### ISSUE THREAD

**Issue by erikwestlund** [matfish2/vue-tables#45]
- Vue.js version:  1.0.24
- consumed using: (browserify/webpack/pre-compiled):  Browserify
- FULL error message (including stack trace): 

admin-bf5856199e.js:53903 Uncaught TypeError: this.$refs.file_manager.refresh is not a functionrefresh @ admin-bf5856199e.js:53903(anonymous function) @ admin-bf5856199e.js:44024
backend.js:1 [vue-devtools] Ready. Detected Vue v1.0.24

- relevant code:

server table run as:  `<file-manager feed="feed" v-ref:file_manager></file-manager>`

which calls a child component where the template has the server table code.

Then I have a div like so:

`<div class="dropzone" id="dropzone-uploader" @click="refresh"></div>`

I click that, and it fires method on parent vue:

>         reloadData: function() {
>             console.log(this.$refs.file_manager);
>             this.$refs.file_manager.refresh();
>         }  
> 

That last method runs and logs the server object.  Which I look through and do not see a method for refresh

I feel like I'm missing something obvious.

**Comment by erikwestlund** [comment]
I was able to make it work with the following command:

this.$refs.file_manager.$children[0].refresh()


Is this what you had in mind?  Is there a way to explicitly call refresh without fishing out the 0th element of the childrne array?

**Comment by erikwestlund** [comment]
So I'm not very good at this.  I wonder if you'd have a better solution to this.  


I have a dropzone.  Dropzone allows you to fire events on a successful upload -- after all files have loaded on the server.  I am able to succesfully fire an event using javascript or jquery afterwards.  The hack I've done now is to have a hidden element, and on a successful upload, i simulate a click on a hidden div.  That div has @click, which fires a method to refresh the vue tale using:

this.$refs.file_manager.$children[0].refresh()

It works.  But it seems like a hack.  I don't know of a better solution.  Is there a more elegant way using event listeners?

**Comment by matfish2** [comment]
You can save you instance to a variable (e.g `var vm = new Vue({})` etc. and then directly interact with it from within the upload success event.
