### ISSUE TITLE
Search is available?

### ISSUE THREAD

**Issue by NightZpy** [matfish2/vue-tables#47]
Search for a textfield like jquery datatable?
Pass api url for order, search?

**Comment by matfish2** [comment]
I don't understand

**Comment by NightZpy** [comment]
Ok, excuse me!
vue-tables have feature like jquery datatables: search, order from server?

**Comment by matfish2** [comment]
As you can see in the docs there are 2 separate components for the client and the server side.
Please read the docs.

**Comment by NightZpy** [comment]
I know, but don't understand how use this feature :(
You have some example?

**Comment by matfish2** [comment]
There is an example in the docs how to use the server component.
On the server side of course you need to write your own code to manage the request and return the correct response. You can see an example for this in the eloquent implementation that I have included. All of this is mentioned in the docs.
