### ISSUE TITLE
Dynamic columns?

### ISSUE THREAD

**Issue by jgog** [matfish2/vue-tables#49]
- Vue.js version: 1.0.24
- consumed using: webpack

I am trying to build a table with a few columns predefined and then pushing a few more columns after AJAX, but it doesn't seem to work. 

Anything I should be keeping in mind or is it a bug?

**Comment by matfish2** [comment]
It's not a bug, simply unsupported.
The `columns` prop is not used directly, because the total columns include custom columns as well. 
It doesn't seem like a common use-case, but if others will ask for this feature I may implement it.

**Comment by michalisantoniou6** [comment]
Hey @matfish2, is there documentation on how to use reactive columns?

Thanks a lot in advance.
