### ISSUE TITLE
Server side table

### ISSUE THREAD

**Issue by HenoTaMyJIb** [matfish2/vue-tables#50]
Is it possible to disable server request (data load) on page/component init?
So user could set some search filters and then load data (this.$refs.table.refresh()).

Is it possible and is this making sense to add something like this?
```
this.$refs.table.refresh({
      startdate: %value from form input%,
      enddate: %value from form input%
})
```

Send parameters from external form.

**Comment by matfish2** [comment]
The components are not designed to search from scratch.  
Possible way around: 
Use custom filters to send some sort of flag along with the query, when the user is ready to search, and on the server side utilize this flag to decide whether to continue or return an empty dataset. You will need to change the text for `noResults` to signify that a search was not yet performed. After the first search change the text to denote that no results were found (Change it on the component level for it to take effect).
