### ISSUE TITLE
Template function

### ISSUE THREAD

**Issue by HenoTaMyJIb** [matfish2/vue-tables#52]
Hi, thank you for vue-tables.

There is another question.

On "VueTables Options API" page, there is an example

```
templates: {
  edit:"<a href={id}><i class='fa fa-edit'></i></a>",
  age:function(row) {
       return this.calcAge(row.birth_date);
  } 
}
```

In this case `this` doesn't refer to a Vue instance?
Where method calcAge should be defined? Or am I doing something wrong?
https://jsfiddle.net/w7u7tf7p/

**Comment by matfish2** [comment]
It is merely an example, not copied from the demo fiddle.

**Comment by HenoTaMyJIb** [comment]
Wrong link.
https://jsfiddle.net/w7u7tf7p/2/

Implement like this? 
```
methods: {
    deleteMe: function(id) {
      alert("Delete " + id);
    },
	calcAge: function(date) {
            var age = 0;
            // calculations
    	    return age;
        }
  },
```

Getting `is not a function` error

**Comment by matfish2** [comment]
It appears that `this` inside the function refers to the window object. 
I suppose you can use a global function or simply write the logic in the template function.

**Comment by HenoTaMyJIb** [comment]
Thank you for help!

**Comment by matfish2** [comment]
I have added the root vue instance as the `this` context for the function. Now you CAN use `this.calcAge` inside the function.
