### ISSUE TITLE
Getting column when data array has a "sub-object"

### ISSUE THREAD

**Issue by jonnywilliamson** [matfish2/vue-tables#53]
- Vue.js version: 1.0.24
- consumed using: pre-compiled
- FULL error message (including stack trace): N/A
- relevant code:

https://jsfiddle.net/n5484gbk/1/

Each item in my DATA array looks like this:
```js
{
  FlightDep: "MCO",
  FlightArr: "DUB",
  FlightAcType: "330",
  FlightDesc: "EI120",
  positionCount: {
    CP: 1,
    FO: 3,
    SU: 1,
    SN: 1,
    CC: 6,
  }
}
```

I want columns for `FlightDesc`, `FlightDep` and (for example) the `CP` section of the `positionCount` property.

In my vue code I have:

```js
  data: {
    columns: ['FlightDesc', 'FlightDep', `positionCount.CP`],
    options: {
         ///Options in here
     }
```

However when I run this, I get three columns but the last column isn't showing the correct (or any) data `positionCount.CP`.

How do I access the `positionCount.CP`, `positionCount.FO` etc etc as columns?

**Comment by jonnywilliamson** [comment]
Just updated the question. I hit submit too early. Sorry!

**Comment by matfish2** [comment]
The plugin doesn't support multidimensional data. 
You can use a template on this column to display the data.

**Comment by jonnywilliamson** [comment]
>The plugin doesn't support multidimensional data. 

Do you accept feature requests?!

**Comment by matfish2** [comment]
If the feature request is clear and elaborated I will consider it.

**Comment by Doogiemuc** [comment]
Even in a template I cannot access the sub-documents.  Starting from your (awesome!) fiddle: https://jsfiddle.net/matfish2/f5h8xwgn/   Let's asume, that the data contained sub documents, e.g.

```
tableData: [{
      id: "1",
      name: "Sidney Brakus",pet:randomOption(),
      some_sub_doc: { foo: 'bar' },      
      birth_date: randomDate(new Date(1925, 0, 1), new Date(2012, 0, 1))

    }, {
      id: " ...
```

Then I tried in my template:

`someColumn: "{some_sub_doc.foo}"`

and expected it to show the value 'bar'.  But apparently this dot notation is not supported.

**Comment by Doogiemuc** [comment]
As already mentioned in other "issues":   A perfect general solution would be, if a template function could somehow receive the data for the whole row. Then anything would be possible.
