### ISSUE TITLE
Columns added by template aren't sortable even if option is enabled.

### ISSUE THREAD

**Issue by jonnywilliamson** [matfish2/vue-tables#54]
- Vue.js version: 1.0.24

- consumed using: pre-compiled

- FULL error message (including stack trace):
N/A

- relevant code:

https://jsfiddle.net/cjkztaos/2/

- steps for reproducing the issue:

Run the jsfiddle and try and sort the Captain or Copilot column. 

This is probably related to https://github.com/matfish2/vue-tables/issues/53

I am adding a few custom columns to my table using the `template` option. This appears to be working as I can see the data in the table.

I do however want to be able to click on these columns and be able to sort them. So I read the docs and added the `sortable` array option.

Still though, I can't seem to be able to sort by these custom/template columns, even if the normal columns are sortable.

Am I doing something wrong or is this a limitation I'm hitting?

**Comment by matfish2** [comment]
This is by design. Sorting is only enabled on original data.
Since custom columns don't exist in the original dataset in their compiled form, vue's `orderBy` filter cannot sort by them (go to `sortable.js` and remove the restriction to see for yourself).

**Comment by jonnywilliamson** [comment]
Ok thank you.
