### ISSUE TITLE
move pagination and rows per page to different spots

### ISSUE THREAD

**Issue by Roas** [matfish2/vue-tables#57]
Hey! I was playing around with your plugin and it's amazingly build. Just one question I had.

Is it possible to move the pagination and rows per page dropdown to different spots and maybe give them a bit different design? I want to put it into a design I already have.

**Comment by matfish2** [comment]
The HTML template is hardcoded.
As for design you can write your own CSS, or override bootstrap's.

**Comment by cloud9business** [comment]
Perhaps the name of the hard-coded template could be made configurable. So that table-template.html could be replaced with a customised version.

**Comment by matfish2** [comment]
See PR #83
