### ISSUE TITLE
Any chance for class display control?

### ISSUE THREAD

**Issue by litan1106** [matfish2/vue-tables#59]
Any chance for class display control?

https://datatables.net/extensions/responsive/examples/display-control/classes.html

**Comment by matfish2** [comment]
This is built on top of issue #49 (reactive columns prop).
I plan to implement it in the (hopefully near) future.

**Comment by matfish2** [comment]
I have added a `columnsDisplay` option. See the [Options API ](https://jsfiddle.net/matfish2/bp1g4khr/)for details.

**Comment by litan1106** [comment]
@matfish2 Awesome, thanks.
