### ISSUE TITLE
Query parameters are not passed to the server

### ISSUE THREAD

**Issue by roed** [matfish2/vue-tables#64]
- Vue.js version: 1.0.26
- consumed using: browserify
- FULL error message (including stack trace): none

The query parameters are not passed to the backend in our project. So if you do any filtering/searching/paginating the data is not passed to the backend.

For the server-table, you have in your package.json:
"vue-resource": "^0.7.4"
We use: 0.9.1, which matches your requirement

If we change the following line in file: `lib/methods/get-data.js`
````
return this.$http.get(this.url, data );
//to
return this.$http.get(this.url, { params: data} );
````
It works. The release list for vue-resource states that there is a breaking change that caused this in version 0.9:
https://github.com/vuejs/vue-resource/releases

I don't know what you want to do with this, but clearly your library is affected by this breaking change.

**Comment by matfish2** [comment]
Thanks. I've updated the package accordingly.
