### ISSUE TITLE
if i want to sent something  like userId (except limit,orderBy,ascending,page,byColumn)to the server side in v-server-table，where should i write the param

### ISSUE THREAD

**Issue by nigulasikk** [matfish2/vue-tables#65]
- Vue.js version:
- consumed using: (browserify/webpack/pre-compiled)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

**Comment by matfish2** [comment]
Additional parameters can be sent using [server-side filters] (https://github.com/matfish2/vue-tables#server-side-filters). 
Sending a user id through is very dangerous, and can be easily manipulated by the user. Your source of truth for this kind of sensitive data should be server-side only.

**Comment by matfish2** [comment]
I've added a params option. See the Options API.

**Comment by nigulasikk** [comment]
thanks ~
