### ISSUE TITLE
How to apply class to table rows

### ISSUE THREAD

**Issue by quebecCu** [matfish2/vue-tables#66]
- Vue.js version: 2.0
- consumed using: webpack

Is there a way to apply bootstrap table class to table row regarding a condition. 

For example, apply this class : 
`<tr class="table-warning">...</tr>`
if one of my data in this row meets a condition.

**Comment by matfish2** [comment]
Not at the moment.
You can fork the repo and change the template to your liking.

**Comment by phaberest** [comment]
Just in case anyone need it, I've faced the same problem and solved it using jquery.

```
<script>
    $(function () {
        $("#shipments tr").has("td:contains('Non ancora ordinata')").addClass('bg-red-haze');
        $("#shipments tr").has("td:contains('Richiesta')").addClass('bg-red-haze');
        $("#shipments tr").has("td:contains('In attesa di ritiro')").addClass('bg-red-haze');
        $("#shipments tr").has("td:contains('Ritirata')").addClass('bg-red-haze');
        $("#shipments tr").has("td:contains('In consegna')").addClass('bg-red-haze');
        $("#shipments tr").has("td:contains('Spedita')").addClass('bg-red-haze');
        $("#shipments tr").has("td:contains('In errore')").addClass('bg-red-haze');
        $("#shipments tr").has("td:contains('Rimborsata')").addClass('bg-red-haze');
    });
</script>
``` 

Where `#shipments` is my vue-tables container `div` and inside `contains()` you say what's displayed inside a td.
