### ISSUE TITLE
Question: How to add a hover event on table cells?

### ISSUE THREAD

**Issue by Doogiemuc** [matfish2/vue-tables#70]
Hello there! Thank you very much for your awesome component vue-tables.

In my project I would like to implement editing of table **cells**.  (I know that there already is an onRowClick event that could be used to start editing a whole row. But I need to edit single cells.)

What I have:

For editable rows, I have a template that shows an edit icon when the user hovers over a cell:

```
template: {
  editableValue: '{editableValue}<span class="glyphicon glyphicon-edit pull-right hidden" style="cursor:pointer"></span>'
}
```

How do I make the icon appear, when the user hoves over that **cell**?  How do I attach the `onmouseenter` and `onmouseleave` events to the parent element of editableValue, ie the <TD> elem ?

**Comment by Doogiemuc** [comment]
Some thoughts:
"brute force":  I could use JQuery and simply attach all necessary events, when the table has loaded completele.  But I think this is the wrong aproach.  I'd would break in combination with pagination. 

There must be a "vuejs" way?

**Comment by matfish2** [comment]
There is a CSS way...

```
td:hover .edit-icon {
  display:block;
}

```
