### ISSUE TITLE
Q: Is vie-tables working with Vu2.js 2.0 ?

### ISSUE THREAD

**Issue by jrondorf** [matfish2/vue-tables#71]
Hi, loving the vue-tables.
I am planning to use Vu2.js 2.0, are vue-tables working with that already?
Thanks!

**Comment by matfish2** [comment]
Not yet. Hopefully soon.

**Comment by jrondorf** [comment]
If you need help, let me know.

**Comment by matfish2** [comment]
Done: https://github.com/matfish2/vue-tables-2

**Comment by jrondorf** [comment]
Great! Did you test with Bootstrap 4 alpha also ?
