### ISSUE TITLE
Versions 1.41 and 1.4.5 sends broken queries with extra "param" tags in vue tables server

### ISSUE THREAD

**Issue by erikwestlund** [matfish2/vue-tables#72]
- Vue.js version: 1.0.26
- consumed using: (browserify/webpack/pre-compiled)   webpack
- FULL error message (including stack trace):  no error message
- relevant code:  n/a
- steps for reproducing the issue:

laravel elixir 6.0.0-9
using webpack
vue-tables

On versions 1.42 and 1.4.5, the ajax query when using vue-tables with a server is malformed:

it sends:  ?params%5Bquery%5D=&params%5Blimit%5D=25&params%5BorderBy%5D=id&params%5Bascending%5D=1&params%5Bpage%5D=1&params%5BbyColumn%5D=0

I confirmed this versions 1.42 and 1.4.5, each time doing a complete re-install of node modules.  

Note all the instances of "params%5B".

When I lock the version to 1.4.41 in package.json, the problem goes away. This affects filtering and the initial call.

I suspect this has something to do with the commits 6 days ago related to sending extra server params.

**Comment by matfish2** [comment]
you need to use vue-resource v0.9.0 or greater. See #64.
