### ISSUE TITLE
vue-tables 1.4.5

### ISSUE THREAD

**Issue by erikwestlund** [matfish2/vue-tables#73]
- Vue.js version: 1.0.26
- consumed using: (browserify/webpack/pre-compiled): webpack
- FULL error message (including stack trace):

add-custom-columns.js?9659:3Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined(…)
module.exports @ add-custom-columns.js?9659:3
(anonymous function) @ vue.common.js?4a36:216
module.exports @ set-data.js?5d58:5
(anonymous function) @ vue.common.js?4a36:216
(anonymous function) @ v-server-table.js?3cd8:65

- relevant code:

 <v-server-table url="/admin/users/fetch" :columns="columns" :options="options" v-ref:users_table>
 </v-server-table>

in my component that calls v-server-table:

data() {
    return {
        columns: ['id', 'username', 'email', 'joined', 'modified', 'deleted', 'edit', 'delete'],
        options: {
            filterable: ['username', 'email'],
            'orderBy.column': 'username',
            templates: {
                id: function(row){
                    return '<input type="checkbox" name="items_selected" id="' + row.id + '" class="item_checkbox" onClick="check_if_deletion_buttons_needed()" value="' + row.id + '">';
                },
                username: function(row) {
                    if(row.deleted) {
                        return '<del>'  + row.username + '</del>';
                    }

                    return row.username;
                },
                edit: function(row) {
                    if(!row.deleted){
                        return '<a role="button" href="/admin/users/' + row.id + '/edit" class="btn btn-xs btn-success"><i class="fa fa-edit"></i> <span class="action-label">Edit</span></a>'                                }
                    return '';
                },
                delete: function(row) {
                    if(row.deleted) {
                        return '<button type="button" class="btn btn-xs btn-info" @click="$parent.restoreUserModal(\'' + row.id + '\', \'' + row.username + '\')"><i class="fa fa-life-ring fa-lg"></i><span class="action-label">Restore</span></button>';
                    }
                    return '<button type="button" class="btn btn-xs btn-danger" @click="$parent.deleteUserModal(\'' + row.id + '\', \'' + row.username + '\')"><i class="fa fa-trash fa-lg"></i><span class="action-label">Delete</span></button>';
                }
            }
        }
    }
}

There is a correct network call and response with the column datta.

It looks like the "customColumns" array is not getting populated.

this was functioning correctly in 1.4.41 and vue resource 0.7

**Comment by matfish2** [comment]
Odd. I am using the same version in my own project, including custom columns.
Can you add a `console.log(this.customColumns)` before the `forEach` call in `add-custom-columns.js`, and paste the output? You should be getting an empty array, since you are already passing the custom columns into your main `columns` prop.
 Also, go to the `template-keys.js` file and `console.log(Object.keys(this.options.templates))`
