### ISSUE TITLE
Server mode, Laravel + model data

### ISSUE THREAD

**Issue by jackmcdade** [matfish2/vue-tables#75]
How do you I render any columns that use Model data that isn't directly pulled from the database?

**Comment by matfish2** [comment]
Do you mean custom mutators on the model?

**Comment by jackmcdade** [comment]
Yes, or any extra methods for that matter. `$model->getSomething()`

**Comment by matfish2** [comment]
Do you mean custom mutators on the model that generate derivative attributes?

**Comment by matfish2** [comment]
Do you mean custom mutators on the model that generate derivative attributes?

**Comment by matfish2** [comment]
Do you mean custom mutators on the model that generate derivative attributes?

**Comment by matfish2** [comment]
Do you mean custom mutators on the model that generate derivative attributes?

**Comment by jackmcdade** [comment]
Yes, any of those.

**Comment by matfish2** [comment]
Well, If I remember correctly custom mutators are attached by laravel to the query results. Any other data would have to be manually parsed by you before you return the results.
