### ISSUE TITLE
Last 2 releases broke my code

### ISSUE THREAD

**Issue by decebal** [matfish2/vue-tables#76]
- Vue.js version:
- consumed using: (browserify/webpack/pre-compiled)
- FULL error message (including stack trace):
- relevant code:
- steps for reproducing the issue:

First time adding params and not making it backward compatible before all filters made it incompatible. 

Now I get this little one: `Uncaught (in promise) TypeError: data.json is not a function(…)`

**Comment by matfish2** [comment]
Update `vue-resource` to the last version. As the docs now state it requires 0.9.0 or greater.
This will also remove the `params` wrapper.

**Comment by decebal** [comment]
sorry for beeing acid.. I was in a time crisis

**Comment by phaberest** [comment]
It breaks with [axios](https://github.com/mzabriskie/axios) too. 😞

**Comment by matfish2** [comment]
It doesn't support `axios`. As mentioned in the docs it *requires* `vue-resource` (<=0.9.0).
I intend to implement a more agnostic approach, like I did in version 2 of this package (vue-tables-2).

**Comment by phaberest** [comment]
That sounds weird to me, I switched from vue-resource to axious declaring it as `Vue.prototype.$http = axios;` and didn't have to touch a single file.

The api are pretty the same...

I'll dig into it to see if I can help you with a PR, maybe it's just how you read the json that comes from the promise
