### ISSUE TITLE
Table not reload after data refresh with an api

### ISSUE THREAD

**Issue by Alaurent333** [matfish2/vue-tables#78]
- Vue.js version: v1.0.26
- Vue ressource version : v0.9.3
- Vue Tables version : v1.4.53
- consumed using: pre-compiled
- FULL error message (including stack trace): TypeError: data is undefined (After new data)

Hi,
I have a simple app : 
`<div id="app">
  <button type="button" class="btn btn-primary" v-on:click="recupCnt()">Primary</button>
  <v-client-table :data="tableData" :columns="columns" :options="options"></v-client-table>
</div>`
I want to refresh tableData with api like this : 
```
Vue.use(VueTables.client, {
  filterByColumn: true,
  texts: {filter: "Rechercher :", filterPlaceholder:"...",noResults:"Aucun résultat trouvé",filterBy: ""}
}); 

var vue=new Vue({
  el:"#app",
  data: {
    columns:['Numcnt','Categorie','Userid','Respid'],
    tableData: [],
    options: {}
  },
  methods: {
	  recupCnt: function(){ 
      this.$http.get('/api/V1/contratsUser').then(function(res){
            this.tableData=res.data
      }.bind(this)); 
    }
  }
});
```
But it's not working and after call recupCnt function, in the console i have this error :
![vue-tables-error](https://cloud.githubusercontent.com/assets/3605501/16942632/6cbd9212-4d97-11e6-8f45-ef51c4634db8.png)
But this error appear only when i load some New Data into tableData not before.

**Update :  With vue-resource 0.8 it's work but not with >= 0.9 : /**

Cordially,
Laurent.

**Comment by matfish2** [comment]
Vue resource had some breaking changes in v0.9.0.
My bet is that your `data` property returns as a string, not an object. Try using `res.json()` instead of `res.data`. That is what I did in the server component.
