### ISSUE TITLE
Full webpack config for creating minified file

### ISSUE THREAD

**Issue by randarp** [matfish2/vue-tables#79]
- Vue.js version: 1.0.26
- consumed using: webpack and pre-compiled

I've been trying to figure out the webpack config to generate the same file as the pre-compiled version from the node package.  https://github.com/matfish2/vue-tables/issues/23 has minimal detail .

This is what I have,

    return gulp.src('node_modules/vue-tables/index.js')
        .pipe(webpackstream({
            module: {
                loaders: [
                    { test: /\.html$/, loader: 'vue-html' }
            ]},
            output: {
                path: __dirname,
                filename: "vue-tables.min.js",
                library: 'VueTables',
                libraryTarget: 'var'
            },
            plugins: [
                new webpack.optimize.UglifyJsPlugin({minimize: true})
            ]
        }
        ))
        .pipe(gulp.dest('public/js/vendor/'));

It seems to generate something that works (at first glance), but it is quite different from the pre-compiled version when doing a file compare.  I'm assuming the difference is webpack vs. browserify?

**Comment by matfish2** [comment]
I am not familiar with `webpack`.  I used `browserify` to compile the minified version.
Obviously the compilers are not identical, so there is no point in comparing the outputs.
