### ISSUE TITLE
No (clean) way to disable sorting?

### ISSUE THREAD

**Issue by cosmin** [matfish2/vue-tables#84]
As far as I can tell there is no way to disable sorting entirely. I tried setting `sortable = []` in `options` but that did not accomplish anything. I worked around it by setting `sortable = ["made_up_column"]` which had the desired effect but hardly seems like the right way to do it. Am I missing something about the right way to do this?

**Comment by lukpep** [comment]
@cosmin 
I'm using` sortable: [''],` in options object
