### ISSUE TITLE
Disable all pagination

### ISSUE THREAD

**Issue by judgej** [matfish2/vue-tables#85]
- Vue.js version: 1.4.0
- consumed using: just in my web page
- FULL error message (including stack trace): n/a
- relevant code: n/a
- steps for reproducing the issue: n/a

I just want the table to display everything it was been given, with no paging and no page size selection.

The built-in template displays the "Records" dropdown to select the page size, and displays a pager at the bottom of the table. There appears no simple way to disable that, apart from replacing the default template.

Am I missing something, or is this an option not available?

**Comment by matfish2** [comment]
You can use css to hide it, or  a custom template (see docs)

**Comment by judgej** [comment]
I was trying to avoid creating a custom template, since the template forms the majority of what this component provides. CSS is a poor approach, since it just hides what is still there.

I'll go for a custom template, but it may turn out easier just to code the table without this component (which is a shame).
