### ISSUE TITLE
didn't work with another vue delimiters 

### ISSUE THREAD

**Issue by xuziding** [matfish2/vue-tables#86]
- Vue.js version:1.02
- consumed using: pre-compiled
- relevant code:
```
Vue.config.delimiters = ['${', '}']
Vue.config.unsafeDelimiters = ['{!!', '!!}']
Vue.use(VueTables.client, {
	compileTemplates: true,
	highlightMatches: true,
.......
```
the result is error.
i think  replace "{{" to Vue.config.delimiters[0] and "}}" to Vue.config.delimiters[0] ,How i do that ? thanks

**Comment by matfish2** [comment]
Of course it won't work. The template is using the default delimiters.
You can customize the template to use your own delimiters:
a. Copy `table-template.html` to a new file
b. change all delimiters
c. use the `template` option to pull your template
