### ISSUE TITLE
Dependency on module `stringify`

### ISSUE THREAD

**Issue by vernard** [matfish2/vue-tables#88]
- Vue.js version: ^1.0.26
- consumed using: (browserify/webpack/pre-compiled) browserify
- FULL error message (including stack trace):

[23:40:22] gulp-notify: [Laravel Elixir] Browserify Failed!: Cannot find module 'stringify' from 'D:\Side\susy-test\node_modules\vue-tables'
{ Error: Cannot find module 'stringify' from 'D:\Side\susy-test\node_modules\vue-tables'
    at D:\Side\susy-test\node_modules\resolve\lib\async.js:46:17
    at process (D:\Side\susy-test\node_modules\resolve\lib\async.js:173:43)
    at ondir (D:\Side\susy-test\node_modules\resolve\lib\async.js:188:17)
    at load (D:\Side\susy-test\node_modules\resolve\lib\async.js:69:43)
    at onex (D:\Side\susy-test\node_modules\resolve\lib\async.js:92:31)
    at D:\Side\susy-test\node_modules\resolve\lib\async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
  stream: 
   Labeled {
     _readableState: 
      ReadableState {
        highWaterMark: 16,
        buffer: [],
        length: 0,
        pipes: [Object],
        pipesCount: 1,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        objectMode: true,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null,
        resumeScheduled: false },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        error: [Object],
        data: [Function: ondata],
        _mutate: [Object] },
     _eventsCount: 4,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        highWaterMark: 16,
        objectMode: true,
        needDrain: false,
        ending: true,
        ended: true,
        finished: true,
        decodeStrings: true,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: false,
        bufferProcessing: false,
        onwrite: [Function],
        writecb: null,
        writelen: 0,
        buffer: [],
        pendingcb: 0,
        prefinished: true,
        errorEmitted: false },
     writable: true,
     allowHalfOpen: true,
     _options: { objectMode: true },
     _wrapOptions: { objectMode: true },
     _streams: [ [Object], [Object] ],
     length: 2,
     label: 'deps' } }

- relevant code: Nothing. basically my script browserify failed when I imported your module.

- steps for reproducing the issue:
Import vue and vue-tables module from your script. It fails because it needs `stringify` module.

Hi, first I want to thank you for this great work. I want to point out a dependency that I didn't notice immediately (until I reread the docs)

Please be explicit that about the dependency on the `stringify` module. This issue was fixed once I executed `npm install stringify`.

**Comment by matfish2** [comment]
I was explicit. From the docs:

Compile the code using `browserify` with the `stringify` transform, or `webpack`

**Comment by vernard** [comment]
What I meant was adding that item on the "Dependencies" list then saying (if compiled with browserify).

Anyway, this is fine. Thanks
