### ISSUE TITLE
iPhone scroll issue

### ISSUE THREAD

**Issue by ElementLi** [matfish2/vue-tables#89]
- Vue.js version:1.0.18
- consumed using: webpack
- steps for reproducing the issue: When use tables on iPhone, it not scroll when tap and scroll on the table area, scrollable outside of the table area. If you tap scroll on the table for three times, the table becomes scrollable.

**Comment by matfish2** [comment]
This sounds to me like a pure CSS problem, and thus has nothing to do with the plugin.
If you do find that the solution involves changes in the HTML template, let me know or send a PR.
