### ISSUE TITLE
Get filtered collection

### ISSUE THREAD

**Issue by stefandb** [matfish2/vue-tables#92]
- Vue.js version: 1.0.26
- consumed using: browserify

Is het possible to get the filtered collection in a function placed in lib/methods? 
I need this to be able to generate an export.

**Comment by matfish2** [comment]
I don't understand your question. Please elaborate: What is it that your are trying to accomplish?

**Comment by GaborSuranyi** [comment]
Yep, this would be really useful!

Let's say that I have a table of ~1300 invoices.
Upon filtering, the count properly indicates the filtered row count.

Now let's say that I would like to also show next to the current, filtered count, the total sum value of the invoices in the table.

I don't just need simply the rows that I provided to vue-tables, (which I could calculate with, before I pass it tableData) I need the _current, filtered collection_, and pass it into a function, that could perform whatever I need to perform.

- get a sum of a column
- get a sum of types / listColumns (like X male and Y female)
- any other stats I would like to show. Maybe I would like to show a chart next to the table, that shows what the current filtered table has.
- export the current, filtered list as CSV etc.
