### ISSUE TITLE
Problem with templates methods

### ISSUE THREAD

**Issue by KerMiiTT** [matfish2/vue-tables#93]
- Vue.js version:  1.0.26
- techno: MVC4, C#4.5

Hi,

I have a problem when i call a methods on template options.

`templates: {
                    Action: "<a href='#!' @@click='$parent.deleteDocument({Name})'><i class='material-icons'>delete</i></a>"
                },`

When i passed an int in {Name} my method is called, but when i try with a string the method did not call.

n.b: i use double @@click because i use razor asp.net and it work with an other method.
do you an issue for my problem ?

**Comment by matfish2** [comment]
You need to wrap Name with double quotes so it will be interpreted as a
string. The way it is now it is interpreted as a variable name

**Comment by KerMiiTT** [comment]
thank you for your quick response

so like this : `"<a href='#!' @@click='$parent.deleteDocument({{Name}})'><i class='material-icons'>delete</i></a>"` ?

**Comment by KerMiiTT** [comment]
i have tried with this :
`'<a href="#!" @@click="$parent.deleteDocument("{Name}")"><i class="material-icons">delete</i></a>'`

and my methods is ` deleteDocument: function (data) {
                console.log("OK delete" + data);
            }`
but it doesn't word 

i try to change with '<a href="#!" @@click="$parent.deleteDocument("test")"><i class="material-icons">delete</i></a>'
and it same

**Comment by KerMiiTT** [comment]
i have tried on your live demo https://jsfiddle.net/matfish2/f5h8xwgn/ 

i have changed the {id} by 'test' `delete: "<a href='javascript:void(0);' @click='$parent.deleteMe('test')'><i class='glyphicon glyphicon-erase'></i></a>"` 
it's same, it doesn't work, what's wrong ?

**Comment by matfish2** [comment]
You already use single question to wrap the click exprssion. You can't use them again within this expression without escaping or contcatanating. This WILL work:

` "<a href='javascript:void(0);' @click='$parent.deleteMe(" + '"test"' +")'><i class='glyphicon glyphicon-erase'></i></a>"`

**Comment by KerMiiTT** [comment]
thank you very much for your answer , it works perfectly
