### ISSUE TITLE
Catching AJAX error in server table

### ISSUE THREAD

**Issue by calvinmuller** [matfish2/vue-tables#95]
Hi, I am just wondering how I could notify the client on a server error using the v-server-table, seems the promise only caters for a successful call, perhaps an error callback function?

Thanks

**Comment by matfish2** [comment]
I think an event would be a better course of action, because a user-defined callback will not have access to the all-important contextual `this` (for the same reason I am thinking of changing the `onRowClick` option to a `row-clicked` event). It will also be more in line with the `loaded` event.

**Comment by calvinmuller** [comment]
even better idea. thanks!

**Comment by matfish2** [comment]
Added a 'vue-tables.error' (and `vue-tables.row-click`) event(s)
