### ISSUE TITLE
compatibility with vue-resource v1.0.0

### ISSUE THREAD

**Issue by mullet1989** [matfish2/vue-tables#96]
- Vue.js version: 1.0.26
- consumed using: browserify
- FULL error message: "Uncaught (in promise) TypeError: Cannot read property 'forEach' of undefined(…)"

I was having some trouble getting this component working with a larger vue app using vue-resource v1.0.0. Rolling back to v0.9.0 seemed to fix the issue with the server-side implementation. The error message is above, from what I can deduce it seems to be an issue resolving a promise. Thanks!

**Comment by matfish2** [comment]
For some reason the `then` callback is not invoked when the response is back, even though according to their docs there was no breaking change in the API. 
Until I figure this out I have limited the version, both in the docs and in my package.json  to <1.0.0

**Comment by mullet1989** [comment]
Thanks @matfish2. I hope that you're able to patch it.
