### ISSUE TITLE
Asynchronous pagination?

### ISSUE THREAD

**Issue by metamet** [matfish2/vue-tables#99]
I am wondering if there is a way to enable async pagination. As our database grows, I would like to do a new Ajax request for each page instead of returning the entire query on page load. 

I am using .NET MVC, and it wouldn't be hard to include a param in the Controller if it were possible to pass it through with the pagination requests. 

I didn't see this mentioned anywhere in the documentation, so sorry if I missed that.

**Comment by matfish2** [comment]
That is exactly what the [server component](https://github.com/matfish2/vue-tables#server-side) is for
